// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg6mzhS_f0iOk35LjkVATgvjKvaV3gHOM',
    appId: '1:881779990152:web:aa74a12f93f77ff79f893d',
    messagingSenderId: '881779990152',
    projectId: 'oyuntan-flutter',
    authDomain: 'oyuntan-flutter.firebaseapp.com',
    storageBucket: 'oyuntan-flutter.firebasestorage.app',
    measurementId: 'G-WYFV1PS16F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6q2pQPao-2g_V_gnxvpVGrFkZrpmCIIQ',
    appId: '1:881779990152:android:15663538c7c3edd59f893d',
    messagingSenderId: '881779990152',
    projectId: 'oyuntan-flutter',
    storageBucket: 'oyuntan-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQBtXWMyukzho25i2CTaiHC3kgVZBDnk',
    appId: '1:881779990152:ios:28f6f6f3670824dd9f893d',
    messagingSenderId: '881779990152',
    projectId: 'oyuntan-flutter',
    storageBucket: 'oyuntan-flutter.firebasestorage.app',
    iosBundleId: 'com.example.oyuntan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQBtXWMyukzho25i2CTaiHC3kgVZBDnk',
    appId: '1:881779990152:ios:28f6f6f3670824dd9f893d',
    messagingSenderId: '881779990152',
    projectId: 'oyuntan-flutter',
    storageBucket: 'oyuntan-flutter.firebasestorage.app',
    iosBundleId: 'com.example.oyuntan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg6mzhS_f0iOk35LjkVATgvjKvaV3gHOM',
    appId: '1:881779990152:web:e4fbf0a74287f1759f893d',
    messagingSenderId: '881779990152',
    projectId: 'oyuntan-flutter',
    authDomain: 'oyuntan-flutter.firebaseapp.com',
    storageBucket: 'oyuntan-flutter.firebasestorage.app',
    measurementId: 'G-6FDD0KR5CH',
  );
}
